name: Finance_Residential_Mortgages
description: '2.4 Business use case: Finance Residential Mortgages'
version: 0.0.1
author: nathan+westpac@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: financeresidentialmortgages
  parentArtefactID: pocwestpac
  buildSystem: wheel
  author: null
  createdAt: '2024-05-14 17:00:34'
pipelines:
  pipelines/L0_raw_CSVtoDelta:
    name: L0_raw_CSVtoDelta
    description: Read CSV files into Delta
    author: nathan+westpac@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-05-14 17:00:34'
    datasets:
      inputs:
      - datasets/csv_loan_purpose
      - datasets/csv_origination_system
      - datasets/csv_product_system
      outputs:
      - datasets/L0_raw_loan_purpose
      - datasets/L0_raw_product_system
      - datasets/L0_raw_rule_ID_mapping
      - datasets/L1_raw_origination_system
    subgraphs: []
    dependencies: {}
  pipelines/L1_Bronze_ExactAndInitialEnrichments:
    name: L1_Bronze_ExactAndInitialEnrichments
    description: ''
    author: nathan+westpac@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-05-14 23:51:15'
    datasets:
      inputs:
      - datasets/L0_raw_loan_purpose
      - datasets/L0_raw_rule_ID_mapping
      outputs: []
    subgraphs: []
    dependencies: {}
datasets:
  datasets/csv_loan_purpose:
    name: csv_loan_purpose
    description: ''
    author: nathan+westpac@prophecy.io
    createdAt: '2024-05-14 19:26:44'
    mode: batch
    physicalDatasets:
      Sales-eng:
        fabricId: 11613
        datasetType: File
        description: ''
        author: nathan+westpac@prophecy.io
        createdAt: '2024-05-14 19:26:44'
  datasets/csv_product_system:
    name: csv_product_system
    description: ''
    author: nathan+westpac@prophecy.io
    createdAt: '2024-05-14 19:31:20'
    mode: batch
    physicalDatasets:
      Sales-eng:
        fabricId: 11613
        datasetType: File
        description: ''
        author: nathan+westpac@prophecy.io
        createdAt: '2024-05-14 19:31:20'
  datasets/csv_origination_system:
    name: csv_origination_system
    description: ''
    author: nathan+westpac@prophecy.io
    createdAt: '2024-05-14 19:33:03'
    mode: batch
    physicalDatasets:
      Sales-eng:
        fabricId: 11613
        datasetType: File
        description: ''
        author: nathan+westpac@prophecy.io
        createdAt: '2024-05-14 19:33:03'
  datasets/L0_raw_loan_purpose:
    name: L0_raw_loan_purpose
    description: ''
    author: nathan+westpac@prophecy.io
    createdAt: '2024-05-14 23:47:08'
    mode: batch
    physicalDatasets:
      Sales-eng:
        fabricId: 11613
        datasetType: Database
        description: ''
        author: nathan+westpac@prophecy.io
        createdAt: '2024-05-14 23:47:08'
  datasets/L0_raw_product_system:
    name: L0_raw_product_system
    description: ''
    author: nathan+westpac@prophecy.io
    createdAt: '2024-05-14 23:47:41'
    mode: batch
    physicalDatasets:
      Sales-eng:
        fabricId: 11613
        datasetType: Database
        description: ''
        author: nathan+westpac@prophecy.io
        createdAt: '2024-05-14 23:47:41'
  datasets/L1_raw_origination_system:
    name: L0_raw_origination_system
    description: ''
    author: nathan+westpac@prophecy.io
    createdAt: '2024-05-14 23:48:10'
    mode: batch
    physicalDatasets:
      Sales-eng:
        fabricId: 11613
        datasetType: Database
        description: ''
        author: nathan+westpac@prophecy.io
        createdAt: '2024-05-14 23:48:10'
  datasets/L0_raw_rule_ID_mapping:
    name: L0_raw_rule_ID_mapping
    description: ''
    author: nathan@prophecy.io
    createdAt: '2024-05-20 02:34:18'
    mode: batch
    physicalDatasets:
      Sales-eng:
        fabricId: 109
        datasetType: Database
        description: ''
        author: nathan@prophecy.io
        createdAt: '2024-05-20 02:34:18'
  datasets/L1_bronze_finance_residential_mortgages:
    name: L1_bronze_finance_residential_mortgages
    description: ''
    author: nathan@prophecy.io
    createdAt: '2024-05-20 02:36:03'
    mode: batch
    physicalDatasets:
      Sales-eng:
        fabricId: 109
        datasetType: Database
        description: ''
        author: nathan@prophecy.io
        createdAt: '2024-05-20 02:36:03'
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-05-14 17:00:34'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs:
  subgraphs/Ruleset1:
    name: Enrichments
    description: 'Reusable component for enriching data. '
    author: nathan@prophecy.io
    language: python
    artefactID: ''
    mode: batch
    createdAt: '2024-05-23 03:23:09'
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- type: plibMaven
  modifiedAt: '2024-05-23T01:36:28.008742Z'
  name: plibMaven
  version: 7.1.100
  id: '301823199'
  createdAt: '2024-05-23T01:36:28.008712Z'
- type: plibPypi
  modifiedAt: '2024-05-23T01:36:28.008787Z'
  name: plibPypi
  version: 1.8.23
  id: '1839287552'
  createdAt: '2024-05-23T01:36:28.008777Z'
projectDependencies:
  '224':
    projectUID: 224
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/wDp16mGH_team_30/QWF0O8MX_project_224.git&subPath=
    version: 0.2.17.dev
    isDefault: true
    author: null
    createdAt: '2024-05-18 21:11:29'
  '225':
    projectUID: 225
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/wDp16mGH_team_30/QWF0O8MX_project_225.git&subPath=
    version: 0.0.6.dev
    isDefault: true
    author: null
    createdAt: '2024-05-18 21:11:35'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
