name: Finance_Residential_Mortgages
description: '2.4 Business use case: Finance Residential Mortgages'
version: '1.0'
author: nathan+westpac@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: financeresidentialmortgages
  parentArtefactID: pocwestpac
  buildSystem: wheel
  author: null
  createdAt: '2024-05-14 17:00:34'
pipelines:
  pipelines/L0_raw_CSVtoDelta:
    name: L0_raw_CSVtoDelta
    description: Read CSV files into Delta
    author: nathan+westpac@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-05-14 17:00:34'
    datasets:
      inputs:
      - datasets/csv_loan_purpose
      - datasets/csv_origination_system
      - datasets/csv_product_system
      outputs:
      - datasets/L0_raw_loan_purpose
      - datasets/L0_raw_product_system
      - datasets/L0_raw_rule_ID_mapping
      - datasets/L1_raw_origination_system
    subgraphs: []
    dependencies: {}
  pipelines/L1_Bronze_ExactAndInitialEnrichments:
    name: L1_Bronze_ExactAndInitialEnrichments
    description: Processes loan purpose data by reading, transforming, and integrating
      it with rule mappings and origination system data. It performs lookups to enrich
      the data with additional attributes, joins datasets based on account IDs, and
      applies rule overrides. The pipeline then updates column names, reformats the
      data, and calculates residual terms for residential mortgages before saving
      the final dataset.
    author: nathan+westpac@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-05-14 23:51:15'
    datasets:
      inputs:
      - datasets/L0_raw_loan_purpose
      - datasets/L0_raw_product_system
      - datasets/L0_raw_rule_ID_mapping
      - datasets/L1_raw_origination_system
      outputs:
      - datasets/L1_bronze_finance_residential_mortgages
    subgraphs: []
    dependencies: {}
datasets:
  datasets/csv_loan_purpose:
    name: csv_loan_purpose
    description: ''
    author: nathan+westpac@prophecy.io
    createdAt: '2024-05-14 19:26:44'
    mode: batch
    physicalDatasets:
      Sales-eng:
        fabricId: 11613
        datasetType: File
        description: ''
        author: nathan+westpac@prophecy.io
        createdAt: '2024-05-14 19:26:44'
  datasets/csv_product_system:
    name: csv_product_system
    description: ''
    author: nathan+westpac@prophecy.io
    createdAt: '2024-05-14 19:31:20'
    mode: batch
    physicalDatasets:
      Sales-eng:
        fabricId: 11613
        datasetType: File
        description: ''
        author: nathan+westpac@prophecy.io
        createdAt: '2024-05-14 19:31:20'
  datasets/csv_origination_system:
    name: csv_origination_system
    description: ''
    author: nathan+westpac@prophecy.io
    createdAt: '2024-05-14 19:33:03'
    mode: batch
    physicalDatasets:
      Sales-eng:
        fabricId: 11613
        datasetType: File
        description: ''
        author: nathan+westpac@prophecy.io
        createdAt: '2024-05-14 19:33:03'
  datasets/L0_raw_loan_purpose:
    name: L0_raw_loan_purpose
    description: ''
    author: nathan+westpac@prophecy.io
    createdAt: '2024-05-14 23:47:08'
    mode: batch
    physicalDatasets:
      Sales-eng:
        fabricId: 11613
        datasetType: Database
        description: ''
        author: nathan+westpac@prophecy.io
        createdAt: '2024-05-14 23:47:08'
  datasets/L0_raw_product_system:
    name: L0_raw_product_system
    description: ''
    author: nathan+westpac@prophecy.io
    createdAt: '2024-05-14 23:47:41'
    mode: batch
    physicalDatasets:
      Sales-eng:
        fabricId: 11613
        datasetType: Database
        description: ''
        author: nathan+westpac@prophecy.io
        createdAt: '2024-05-14 23:47:41'
  datasets/L1_raw_origination_system:
    name: L0_raw_origination_system
    description: ''
    author: nathan+westpac@prophecy.io
    createdAt: '2024-05-14 23:48:10'
    mode: batch
    physicalDatasets:
      Sales-eng:
        fabricId: 11613
        datasetType: Database
        description: ''
        author: nathan+westpac@prophecy.io
        createdAt: '2024-05-14 23:48:10'
  datasets/L0_raw_rule_ID_mapping:
    name: L0_raw_rule_ID_mapping
    description: ''
    author: nathan@prophecy.io
    createdAt: '2024-05-20 02:34:18'
    mode: batch
    physicalDatasets:
      Sales-eng:
        fabricId: 109
        datasetType: Database
        description: ''
        author: nathan@prophecy.io
        createdAt: '2024-05-20 02:34:18'
  datasets/L1_bronze_finance_residential_mortgages:
    name: L1_bronze_finance_residential_mortgages
    description: ''
    author: nathan@prophecy.io
    createdAt: '2024-05-20 02:36:03'
    mode: batch
    physicalDatasets:
      Sales-eng:
        fabricId: 109
        datasetType: Database
        description: ''
        author: nathan@prophecy.io
        createdAt: '2024-05-20 02:36:03'
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-05-14 17:00:34'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- type: plibMaven
  modifiedAt: '2024-06-19T08:40:02.184499Z'
  name: plibMaven
  version: 8.1.4
  id: '837185331'
  createdAt: '2024-06-19T08:40:02.184459Z'
  enabled: true
  entity: Project
- type: plibPypi
  modifiedAt: '2024-06-19T08:40:02.18454Z'
  name: plibPypi
  version: 1.9.14
  id: '2024894383'
  createdAt: '2024-06-19T08:40:02.184528Z'
  enabled: true
  entity: Project
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.28
    isDefault: true
    author: null
    createdAt: '2024-09-09 06:17:04'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.8
    isDefault: true
    author: null
    createdAt: '2024-06-19 18:25:48'
  '28005':
    projectUID: 28005
    projectName: Ruleset_FinanceResidentialMortgages
    repositoryPath: gitUri=https://github.com/natetongwong/ruleset_FinanceResidentialMortgages&subPath=/
    version: Ruleset_FinanceResidentialMortgages/2.2
    isDefault: false
    author: null
    createdAt: '2024-06-24 22:35:27'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
